### ISSUE TITLE
Help needed: Failed to execute command for portainer

### ISSUE THREAD

**Issue by AdiTCG** [robwithtech/homelab#1]
**Failed to execute command** 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; docker compose --file '/srv/dev-disk-by-uuid-ba6179cb-c505-4a34-ad28-5f8242c0cd55/Pen64/docker/compose/portainer/portainer.yml' --env-file '/srv/dev-disk-by-uuid-ba6179cb-c505-4a34-ad28-5f8242c0cd55/Pen64/docker/compose/portainer/portainer.env' --env-file '/srv/dev-disk-by-uuid-ba6179cb-c505-4a34-ad28-5f8242c0cd55/Pen64/docker/compose/global.env' up -d 2>&1': time="2024-06-21T13:43:11+05:30" level=warning msg="/srv/dev-disk-by-uuid-ba6179cb-c505-4a34-ad28-5f8242c0cd55/Pen64/docker/compose/portainer/portainer.yml: `version` is obsolete"
service "portainer-ce" refers to undefined volume Pen64/docker/appdata/: invalid compose project

OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; docker compose --file '/srv/dev-disk-by-uuid-ba6179cb-c505-4a34-ad28-5f8242c0cd55/Pen64/docker/compose/portainer/portainer.yml' --env-file '/srv/dev-disk-by-uuid-ba6179cb-c505-4a34-ad28-5f8242c0cd55/Pen64/docker/compose/portainer/portainer.env' --env-file '/srv/dev-disk-by-uuid-ba6179cb-c505-4a34-ad28-5f8242c0cd55/Pen64/docker/compose/global.env' up -d 2>&1': time="2024-06-21T13:43:11+05:30" level=warning msg="/srv/dev-disk-by-uuid-ba6179cb-c505-4a34-ad28-5f8242c0cd55/Pen64/docker/compose/portainer/portainer.yml: `version` is obsolete"
service "portainer-ce" refers to undefined volume Pen64/docker/appdata/: invalid compose project in /usr/share/openmediavault/engined/rpc/compose.inc:805
Stack trace:
#0 /usr/share/php/openmediavault/rpc/serviceabstract.inc(622): OMVRpcServiceCompose->{closure}()
#1 /usr/share/openmediavault/engined/rpc/compose.inc(780): OMV\Rpc\ServiceAbstract->execBgProc()
#2 [internal function]: OMVRpcServiceCompose->doCommand()
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(122): call_user_func_array()
#4 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod()
#5 /usr/sbin/omv-engined(544): OMV\Rpc\Rpc::call()
#6 {main}

I am using your reference yml.
![image](https://github.com/robwithtech/homelab/assets/13999170/d3defc17-ad7d-4feb-9dd7-84306f4292df)

**Comment by robwithtech** [comment]
Something seems off with your "Pen64/docker/appdata/portainer/portainer_data:/data" usually this path start with /srv/dev... or /data or /docker/appdata. On my readme file there is a link to my youtube video where I use this yml file.
